### ISSUE TITLE
$_GET params support

### ISSUE THREAD

**Issue by mensmaximus** [billerickson/display-posts-shortcode#101]
For a project i had to develop a "dynamic" version of "Display Posts Shortcode" to allow the 'order' and 'orderby' attributes values of the shortcode to be populated by $_GET variables from the URL. Therefore I changed line 128 and 129 to

`
$order               = ( !empty( $_GET['order'] ) && $atts['order'] == 'GETVAR' ) ? sanitize_key( $_GET['order'] ) : sanitize_key( $atts['order'] );
$orderby             = ( !empty( $_GET['orderby'] ) && $atts['orderby'] == 'GETVAR' ) ? sanitize_key( $_GET['orderby'] ) : sanitize_key( $atts['orderby'] );
`

I wonder whether supporting $_GET variables for a couple of attributes or even all of theme might be an interesting enhancement.

**Comment by billerickson** [comment]
I like the idea, but don't think it will be added to the core plugin. I try to keep the core plugin as lean as possible with features the majority of users will use, and dynamically changing parameters based on GET variables is beyond the typical users' abilities. 

Also, it has the potential to reveal information the user didn't necessarily want public. 

Instead of directly modifying the plugin, I recommend you use the built-in filters to make the changes so that they won't be lost when the plugin is updated. Here's some tutorials: http://www.billerickson.net/code-tag/display-posts-shortcode/
