### ISSUE TITLE
Can you switch the order of title and image in the output?

### ISSUE THREAD

**Issue by ammist** [billerickson/display-posts-shortcode#127]
Hi there,

I'm an extensive user of the display_posts_shortcode, as well as the Genesis Framework.  I've been using DPS to emulate the creation of archive pages that collect specific tags and other elements.

However, because the structure of Genesis archive page shows the headline and then the image, I can't quite get the formatting to work out.  I want to display the full title ABOVE the image, and the image and excerpt below the title (sort of like how Genesis has entry-header and entry-content sections).

This is totally a feature request, so I understand that you might or might not decide to do it.  But it would be great to specify the order of output of the elements using a shortcode attribute.

Thanks,

Anca.

**Comment by billerickson** [comment]
This is currently doable using the output filter, `display_posts_shortcode_output`. See this example: http://www.billerickson.net/code/add-time-to-display-posts-shortcode/

The filter includes the raw output( `$output`), and all the individual components. You can then return those components in whatever order you want.

However, I really want to rebuild that piece of functionality. I'm not happy with the output filter in its current state because it's become unwieldy (9 separate parameters), and doesn't really work if you have multiple functions modifying the output. 

See [#75 Rebuild the Output Filter](https://github.com/billerickson/display-posts-shortcode/issues/75) for more information.

**Comment by prostoprojekt** [comment]
Great, thats the thing I was looking' at!
