### ISSUE TITLE
When using include_date, display last modified date instead of post date

### ISSUE THREAD

**Issue by jhult** [billerickson/display-posts-shortcode#132]
Original - uses post date
```
if ( $include_date ) 
    $date = ' <span class="date">' . get_the_date( $date_format ) . '</span>';
}
```

Recommended - uses modified daate
```
if ( $include_date ) 
    $date = ' <span class="date">' . get_the_modified_date( $date_format ) . '</span>';
}
```

**Comment by billerickson** [comment]
I'm sorry but that's not the expected behavior. If you would like to use the modified date, I recommend either using the output filter to change the date, or create a custom attributes like `[display-posts include_modified_date="true"]`. Example: http://www.billerickson.net/code/add-time-to-display-posts-shortcode/

**Comment by jhult** [comment]
I was indicating (that in my opinion), the expected behavior should be to show the modified time. That makes more sense than displaying the original post date (again, to me).
