### ISSUE TITLE
Parameter to use a template part

### ISSUE THREAD

**Issue by benoitchantre** [billerickson/display-posts-shortcode#144]
I think it would bring easier customizations for theme authors.
Instead of using multiple parameters and CSS to get something close to an existing template part, you could simply reuse it.

To prevent mistakes from users (infinite loops), an array of whitelisted template parts could be used and part of a specific filter.

What are your thoughts on this?

**Comment by billerickson** [comment]
I like the idea. How do you imagine it working? Would the template part be defined in the shortcode, like `[display-posts template_part="partials/archive" template_part_name="event"]`? Or would it only be accessible via a filter?

What happens when you change themes and the template parts are missing or named differently? If we're specifying the template part in the shortcode itself, all shortcodes will need to be updated.

I think it's possible to implement what you describe using the existing filters. First, define a custom attribute to specify your template part, then in the output filter look for it. Ex: `[display-posts post_type="event" layout="event"]`.

```
/**
 * Using template part
 *
 */
function be_dps_template_part( $output, $original_atts ) {

	// Return early if no layout specified
	if( empty( $original_atts['layout'] ) )
		return $output;

	ob_start();
	if ( 'event' == $original_atts['layout'] ) {
		get_template_part( 'partials/archive', 'event' );

	} elseif ( 'archive' == $original_atts['layout'] ) {
		get_template_part( 'partials/archive' );
	}

	$new_output = ob_get_clean();
	if( !empty( $new_output ) )
		$output = $new_output;

	return $output;
}
add_action( 'display_posts_shortcode_output', 'be_dps_template_part', 10, 2 );
```

You could even use this approach to automatically use a template part based on other query variables, like if `'post_type' == 'event'` use the event partial.


Another benefit to this approach is your template part definition happens inside the theme, where it belongs. When you build a new theme, copy the function over and specify the new template parts for those elements. Or if that doesn't happen, it gracefully degrades back to the standard Display Posts Shortcode output.


I think this is the best approach for now. Maybe when the output filter is rebuilt (#75) I can consider building something in core.

**Comment by benoitchantre** [comment]
Your solution looks great, thank you for the example. Will you add that in the documentation?

I was also thinking of a something based on a filter, because it dependant on the theme and produces cleaner shortcodes.

**Comment by billerickson** [comment]
Great idea. I've updated the wiki: https://github.com/billerickson/display-posts-shortcode/wiki#using-template-parts
