### ISSUE TITLE
Bootstrap columns

### ISSUE THREAD

**Issue by mariusrudolph** [billerickson/display-posts-shortcode#159]
Hi there,
I would like to show the pages in boostrap columns. I changed the wrapper to wrapper="div". What do I need to do that the code looks like that.

`
< div class="container">
< div class="row>
< div class="col-lg-3>page1</div>
< div class="col-lg-3>page2</div>
< div class="col-lg-3>page 3</div>
</ div>
< div class="row>
< div class="col-lg-3>page4</div>
< div class="col-lg-3>page5</div>
< div class="col-lg-3>page6</div>
</ div>
</ div>
`

**Comment by billerickson** [comment]
1. Change the wrapper class. `[display-posts wrapper="div" wrapper_class="container"]`
2. Add the opening/closing div for the row before and after the shortcode using this: https://gist.github.com/billerickson/b43c722f978f80a753bb2c1d728c4762
3. Change the post class to 'col-lg-3', like this: https://gist.github.com/billerickson/95b4aeae746fd74b0cb201f662d6a4a2

Note: you can't start new divs inside the post listing (the second `<div class="row">` in your example). But you shouldn't be doing this anyway because you lose the flexibility of the boostrap grid. You could make it 4 columns on desktop, 3 columns on tablet, and 2 columns on mobile: https://gist.github.com/billerickson/506d1958cd535f87fa8d61919ecc2384

I'm adding `-first` classes for the first post in the row, which you can then style to clear the float. Ex: https://www.billerickson.net/float-clearing-bootstrap-grid/



But after all that, I still recommend you consider the simpler column classes for this plugin. I've even built an add-on plugin ([Columns Extension for Display Posts Shortcode](https://github.com/billerickson/dps-columns-extension)) that lets you specify columns like this: `[display-posts columns="4"]`

**Comment by mariusrudolph** [comment]
Hi, thanks a lot! That worked perfectly! Is there a way how to add the class "img-responsive" to the image automatically?

**Comment by mariusrudolph** [comment]
Hi bill, would there be a solution without the -first clear float solution?

**Comment by billerickson** [comment]
If you know of a better way to clear bootstrap floats, I'm all ears. The only other option I've seen is inserting extraneous markup, like `<div class="col-sm-12">&nbsp;</div>` after every 3 posts, or close out the row and start another one. I don't like that option because you're adding markup that has no content value, only styling value, which is why I prefer a pure CSS approach.

If you must insert markup after certain posts, use the `display_posts_shortcode_wrapper_close` filter.

**Comment by mariusrudolph** [comment]
Hi Bill, thanks a lot! I would prefer to you the bootstrap floats with closing the row. I am not really familiar with "display_posts_shortcode_wrapper_close". Is there a tutorial out there?

**Comment by billerickson** [comment]
There's no tutorial, but here's a link to where the filter appears: https://github.com/billerickson/display-posts-shortcode/blob/master/display-posts-shortcode.php#L541-L549
