### ISSUE TITLE
How to show custom fields?

### ISSUE THREAD

**Issue by noelfloresr** [billerickson/display-posts-shortcode#167]
Is it possible to show native custom fields or advanced custom fields? I don't see any argurments for this. Thanks in advance.

**Comment by billerickson** [comment]
No, there are no parameters for displaying custom fields, but you can use the output filter to modify the output of the shortcode so that it displays anything you like.

[Here's an example](https://www.billerickson.net/code/add-time-to-display-posts-shortcode/). It adds the post's time to the post, but you could just as easily change that to a custom field.
