### ISSUE TITLE
Feature Request: Exclude Sticky Posts by Default

### ISSUE THREAD

**Issue by druesome** [billerickson/display-posts-shortcode#182]
Users of this plugin may be confused when they see extra posts appearing on top of the intended content.

For example, when I used this shortcode to display one post on a page:

```
[display-posts id="341" include_content="true" wrapper="div"]
```

I saw three extra posts on top of it, and it took a while for me to realize they were sticky posts.

I feel that it makes sense to excluded them by default, and just let the user add the ` ignore_sticky_posts="false"` parameter if they want the sticky posts to appear too.

Thank you!

**Comment by billerickson** [comment]
I wish sticky posts were disabled for all WordPress queries by default. But the ultimate goal of this plugin is to replicate the default behavior of WordPress, so I refrain from changing default functionality like this.

I've written an extension plugin called [DPS Exclude Sticky](https://github.com/billerickson/DPS-Exclude-Sticky) that adds this functionality for you, but unfortunately I won't be including it in the core plugin.

**Comment by druesome** [comment]
>so I refrain from changing default functionality like this.

But isn't the default functionality of this shortcode:

[display-posts id="341" include_content="true" wrapper="div"]

is to display only _one_ post with the ID 341?  In your documentation, it says:

>id Specify a specific post ID (or multiple post IDs) to display. Default: empty Example: [display-posts id="9, 10"]

So, it is a little strange that stickies are included.  If there is no intention to exclude them by default, perhaps update the above to something like:

>id Specify a specific post ID (or multiple post IDs) to display. Add the parameter ignore_sticky_posts="true" to exclude sticky posts.  Default: empty Example: [display-posts id="9, 10" ignore_sticky_posts="true"].  

Really appreciate you looking into this!

**Comment by billerickson** [comment]
The default functionality of WordPress is to include sticky posts. If you do a WordPress query like this:

```
$loop  = new WP_Query( array( 'p' => 341 ) );
```

It will return that post **and all sticky posts**. 

The purpose of this shortcode is to mimic the functionality of WordPress queries without having to write code. The [WordPress Query documentation](https://codex.wordpress.org/Class_Reference/WP_Query#Parameters) provides more information on default functionality in queries.

I personally don't like sticky posts, but they are a legacy feature in WordPress. I recommend not using sticky posts because it will affect all queries throughout the site. 

Every parameter listed in the documentation is affected by sticky posts in the same way. 

If you use sticky posts, you will either need to get used to adding `ignore_sticky_posts="true"` or install the [extension plugin](https://github.com/billerickson/DPS-Exclude-Sticky) that adds this for you.
