### ISSUE TITLE
posts_per_page is hardcoded in plugin

### ISSUE THREAD

**Issue by pjohanneson** [billerickson/display-posts-shortcode#234]
In [the documentation on your site](https://displayposts.com/2019/01/07/limit-the-number-of-posts-shown/), you state:

> When displaying a list of posts, Display Posts uses the number you have set in Settings > Reading > “Blog pages show at most” by default.

But that's not quite true. In the code, around line 101, the `posts_per_page` parameter is set to `'10'`; this value is later cast to `(int)` and passed in the `$args` variable.

I was able to work around this by using your `display_posts_shortcode_args` filter, but it would be better, IMHO, to change line 101 (in the [current master branch](https://github.com/billerickson/display-posts-shortcode/commit/f3fea96094be016fb28aa9e2bee68e316f094bbc)) from

`'posts_per_page'        => '10',`

to 

`'posts_per_page'        => get_option( 'posts_per_page', '10' ),`

**Comment by billerickson** [comment]
You're totally correct. When I wrote that documentation I thought I had used `get_option( 'posts_per_page' )` but it looks like I hardcoded it.

I'm hesitant to change it now because it will affect all existing users of the plugin. Someone might be expecting Display Posts to continue showing 10 posts per page even though they have it set to 99 in Settings > Reading. 

I think it would be safer to update the documentation to say it shows 10 by default and explain how you can change it (posts_per_page parameter on the shortcode itself, or a filter to change the site-wide default)

**Comment by pjohanneson** [comment]
Fair enough. Here's the code I used (I just put it in a `mu-plugins` plugin, but it can go anywhere):

```
<?php
/**
Plugin Name: Fix Display Posts shortcode µ
Description: Use the site's 'posts_per_page' option in the shortcode's args.
*/

add_filter( 'display_posts_shortcode_args', function( $args ) {
    if ( ! is_array( $args ) ) {
        return $args;
    }
    $posts_per_page = get_option( 'posts_per_page', 0 );
    if ( ! empty( $posts_per_page ) ) {
        $posts_per_page = intval( $posts_per_page );
        $args['posts_per_page'] = $posts_per_page;
    }
    return $args;
} );
```

**Comment by billerickson** [comment]
I've updated the tutorial on the Display Posts websites to more accurately describe the default, and provide examples of how to change it: https://displayposts.com/2019/01/07/limit-the-number-of-posts-shown/
