### ISSUE TITLE
Underscore in wrapper_class

### ISSUE THREAD

**Issue by acketon** [billerickson/display-posts-shortcode#235]
I'm using display posts shortcode to upgrade from an older custom shortcode and was attempting to avoid CSS changes. However it appears the `wrapper_class` parameter strips underscores from class names. so `wrapper_class="news_list"` is rendered as `class="newslist"`. 

I can work around it but if there isn't a strong reason to sanitize the class names like this it would make it easier to work with existing CSS in themes.

**Comment by billerickson** [comment]
I just tested `[display-posts wrapper_class="testing-wrapper_underscore"]` and didn't have an issue:

![screenshot](https://p198.p4.n0.cdn.getcloudapp.com/items/geu2DgWE/Image%202020-03-26%20at%2011.42.22%20AM.png?v=d1ee59e5c6591a004cea06a3e25e653c)

What version of WordPress are you using?  It looks like this was fixed in WordPress 3.2: https://core.trac.wordpress.org/ticket/17067
