### ISSUE TITLE
Include information about the current 'n' of the post in display_posts_shortcode_output()

### ISSUE THREAD

**Issue by amfriedman** [billerickson/display-posts-shortcode#66]
For this filter, a developer may want to change markup based on the nth child of the current post item relative to the entire set of posts that the shortcode is outputting in a loop. For example, a developer may want to automatically add a "See all posts &raquo;" link after the last item in a list. Can you add a filter parameter that would provide this counter value?

**Comment by billerickson** [comment]
For your specific example, I would instead use the 'display_posts_shortcode_wrapper_close' filter which runs after all posts have been listed. Something like this: https://gist.github.com/billerickson/6d6be7d6bff193bd3895

**Comment by billerickson** [comment]
Also linking this to #75. I don't want to add any more parameters to the already incredibly long output filter (at 9 parameters currently). This needs to be done in a cleaner way. Including the $loop object so that you can see the current location in the loop ( $loop->current_post ) is something that future filter should include.
