### ISSUE TITLE
No results shortcode?

### ISSUE THREAD

**Issue by johannesweb** [billerickson/display-posts-shortcode#87]
display_posts_shortcode_no_results

This is very poorly documented, I don't understand how it works. How do I control what it displays when there's zero results?

**Comment by billerickson** [comment]
In the shortcode you can specify the text that shows up if no results like this:

[display-posts no_posts_message="Sorry, no posts were found."]

The filter you mention allows you to use code to modify this rather than typing it into the shortcode. You could do something like this in your theme: https://gist.github.com/billerickson/f98f9fd0993410f5595d

Then you don't have to include the message in the shortcode. [display-posts] will display the message if it returns no results.

The documentation is a wiki. If you'd like it improved, you can edit the wiki yourself.
