### ISSUE TITLE
Separate PHP and HTML

### ISSUE THREAD

**Issue by powerbuoy** [billerickson/display-posts-shortcode#88]
Nice plug-in. Code looks very complete and clean. However, it would be amazing imo if you would use separate templates for the HTML output, instead of having it all in echo:s.

I wrote a similar one but yours looks much more feature rich and stable, only mine has template support. Perhaps you'll find it useful: https://github.com/powerbuoy/SleekWP/blob/master/inc/get-posts.php, template here: https://github.com/powerbuoy/SleekWP/blob/master/modules/get-posts/list-posts.php

Thanks

**Comment by billerickson** [comment]
If I were to rebuild this plugin today, I'd make it much more modular and filterable. But I don't think I can implement something like this and keep it backwards compatible, especially with all the current filters in place. 

Issue #75 will be my attempt and improving it currently, but since I haven't had a client interested in it I haven't had the time to build anything regarding this. As they say, patches welcome :)
