### ISSUE TITLE
Add new "include_category" parameter

### ISSUE THREAD

**Issue by wladston** [billerickson/display-posts-shortcode#91]
For my application, I also need to display the post's category.

If I create a proper pull request implementing this feature, are you willing to merge it in?

If not, I'll try to create a hack on the post_content filters to make this work. If yes, I'll make a beautiful pull request, also updating the documentation.

Thanks :)

**Comment by billerickson** [comment]
Sure, just try to make it's implementation general enough to be applicable to many different use cases. For instance, you might do something like [display-posts category_display="post_tag" category_label="Tagged as: "] so that you can change out the taxonomy displayed and the text associated with it

**Comment by billerickson** [comment]
[display-posts category_display="true"] displays the listing of categories

[display-posts category_display="my-custom-tax"] displays the listing of terms in 'my-custom-tax' attached to post

[display-posts category_display="color" category_label="Color:"] displays the terms from 'color' taxonomy with an introductory label of "Color:" instead of the default "Posted as:"
